language: node_js
node_js:
- '4.1'
install:
- npm install
script:
- NODE_ENV=production webpack -p
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: FvFmMvsPrpL6CtQBVIsUVJViiBAeT75isrBSNyfYYmJUA9KWujr2WQnwag9QfyrDqEjWaRAfRprcqsX5izphanvfu4MuNPMM3sRSd56eFQ87AX+DGi0yNpN5sPRmlBgPUa26I3LE0GJ97OEF/pyPsKO0SWKSHyMfjl2OAyVyhsaaSJT93ao+QHH009ke7F8N5BTqQhIPlZMehLtDIMvUfa+gYaTzkrcd3U/R5rnlpLFWozSrjtotd27zjazhOEuGWP2uHTpe1sCblQjOSzr6xN/3SFMCAy8U2tPg4wQpzXtMCzyJLuThmKijP2vjvjJa/P2iFH+OcBI1Lej3xJ3K3R8W+yvyLOQhgYRhOrPq7Z6Ri08wXNdiwYztXPUNwLHzFuCVopDSCfSnzuwxcOEP4oHbYda/nLWHGSy5tQTGPKy6ywLw+IZ+vJdHjgCWBOTL7MlqDCN+U8Hn07Wn+U4EIRgy2KNbvxZtqIF/IcsMMTBGqA/jb0NvUibXftEPh4Nq1K1b8vkVSf5spVlINk2Ka6M2KWowyph6m7sqy2mO96iFDt8k0hrOggmGgTJAll3guCFT1f4xP4wVPOFMGzoxZzO0cvZyszZh2+R08F7SJaE5qDf6gqZjYxpfV5B+jRsulQ0rTzotVgPvP5Kz3kI+za5YgXfyaMW5SvjuZZYUjbk=
  app: salty-shelf-54801
  on:
    repo: amituuush/todo-list
